name: 'Manage Heroku Review App'
description: 'Creates or Destroy a Review App in Heroku for the current PR'
inputs:
  action:
    description: 'One of: "create" or "destroy"'
    required: true
    default: 'create'
outputs:
  app_id:
    description: 'The ID of the affected review app'
  web_url:
    description: 'The web_url of the affected review app (only available when action is "create")'
runs:
  using: 'node20'
  main: 'dist/index.js'
